# Generated by Django 5.1.6 on 2025-05-08 19:23

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Treść z HTML (np. <p>, <img>, <h2>)')),
                ('link', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Tytuł do <title>', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text="Opis do <meta name='description'>")),
                ('meta_keywords', models.CharField(blank=True, help_text='Słowa kluczowe, oddzielone przecinkami', max_length=255)),
                ('meta_author', models.CharField(blank=True, default='Majorka Roztocze', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CampingPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_child', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CampingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KayakRentalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kayaks_double', models.PositiveIntegerField(default=10)),
                ('total_kayaks_single', models.PositiveIntegerField(default=0)),
                ('total_waterproof_bags', models.PositiveIntegerField(default=10)),
                ('price_extra_child', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('price_waterproof_bag', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='KayakRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Czas trwania w godzinach')),
                ('price_kayak_double', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('price_kayak_single', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='CabinReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='KayakReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Guest', max_length=255)),
                ('phone_number', models.CharField(default='000-000-000', max_length=15)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('kayak_double_quantity', models.PositiveIntegerField(default=0)),
                ('kayak_extra_child_quantity', models.PositiveIntegerField(default=0)),
                ('kayak_single_quantity', models.PositiveIntegerField(default=0)),
                ('waterproof_bag_quantity', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('kayak_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.kayakroute')),
            ],
        ),
    ]
